// <auto-generated />
namespace RealTalk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifiedpostmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifiedpostmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202102030117095_modified-post-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
