// <auto-generated />
namespace RealTalk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_comments_field_to_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_comments_field_to_post));
        
        string IMigrationMetadata.Id
        {
            get { return "202102041010338_added_comments_field_to_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
