// <auto-generated />
namespace RealTalk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addflaggedtopost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addflaggedtopost));
        
        string IMigrationMetadata.Id
        {
            get { return "202102041918375_add-flagged-to-post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
