// <auto-generated />
namespace RealTalk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedauthorinpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedauthorinpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202102022311173_added-author-in-post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
